# Generated by Django 3.2.24 on 2024-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='soulswon',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='widows',
            name='widowsfed',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='content',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='widows',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
