# Generated by Django 3.2.24 on 2024-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hicoApp', '0002_auto_20240611_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
